server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name : user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db?createDatabaseIfNotExist=true
    username: user_service
    password: e40dcd54-01e2-4899-931f-263b6392d042
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
