server:
  port: # --> port
  servlet:
    context-path: /api/v1

spring:
  application:
    name : user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db?createDatabaseIfNotExist=true
    username: user_service
    password:  # -->
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

#Kafka Producer
kafka:
  bootstrapAddress: ${KAFKA_BROKER_URL:localhost:9092)
  topic:
    UserCreatedMessage
  serializer:
    key: "org.apache.kafka.common.serialization.StringSerializer"
    value: "io.confluent.kafka.serializers.KafkaAvroSerializer"
  schema-registry:
    url: ${SCHEMA_REGISTRY_URL:http://localhost:8081)